### ISSUE TITLE
Support for returning a response object as middleware.

### ISSUE THREAD

**Issue by abhijeetbabar** [data-eden/data-eden#87]
In the current implementation of the Eden Library, I have observed that there is no provision for returning a response object directly from middleware. However, there are certain scenarios where it can be beneficial to have this functionality. For instance, in situations where we want to optimize network performance, we may want to send cached data in the response before making a network call. In such cases, returning a response object from middleware can help to achieve this optimization and improve the overall performance of the application.

**Comment by rwjblue** [comment]
It is already possible to return arbitrary responses from a middleware. I've created https://github.com/data-eden/data-eden/pull/89 to land a test demonstrating this, though the rough tldr; is "don't call next"...

**Comment by hjdivad** [comment]
@abhijeetbabar does @rwjblue's test illustrate what you were looking for?
